# -*- coding: utf-8 -*-
"""CompNeuroProject_lastEXP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JW2ua5DmVxh_QunFURyvlH8PJemN656Z

The distinction between animate and inanimate entities is a fundamental organizing principle of high-level visual cortex: regions along the ventral stream respond selectively to animate categories (faces, bodies, animals), and this distinction emerges early in development and across cultures. A growing literature asks whether deep vision models trained on natural images develop similar category-selective structure, and whether that structure depends on architecture (convolutional vs. transformer) or training objective (supervised classification vs. language-aligned contrastive learning). Here I compare two widely used models — a supervised CNN (ResNet-50) and a vision-language transformer (CLIP ViT-B/16) — for unit-level animate/inanimate selectivity on MemCat, a 10,000-image dataset with human memorability scores. For each model, I compute a d′-based selectivity index on final-layer units, identify the most animate- and inanimate-selective units, visualize their top-activating images and spatial activation maps, and ask whether the top-selective units' activations track human memorability within each animacy category. The goal is not to settle which architecture "better" matches cortex, but to illustrate how animacy representations differ across training regimes and whether those representations carry information about behavioral memorability.
"""

# ============================================================================
# ANIMATE / INANIMATE SELECTIVITY — ResNet50 vs CLIP on MemCat (v7)
# Fixes vs v6:
#   A) selectivity uses pooled within-group SD on raw activations (no global z)
#   B) CLIP feature is the CLS token (with patch-mean kept as a sanity-check pass)
#   C) Cell 12 reuses the models built in Cell 8 (no rebuild)
#   D) Bootstrap CIs use vectorised rank-pair Pearson (≈50× faster)
#   E) Animacy mapping: 'sports' dropped (it's a context category, not animacy);
#      'animate' = {animal} only, 'inanimate' = {food, landscape, vehicle}.
#      Optional: also runs an "animal-only-vs-rest" comparison for transparency.
#   F) Note on Drive workers; recommend copying to local disk if extraction is slow
#
# RESTART RUNTIME BEFORE RUNNING ("Runtime -> Restart runtime -> Run all").
# ============================================================================


# %% CELL 1 — install ---------------------------------------------------------
!pip -q install timm open_clip_torch torch torchvision pandas scipy \
                scikit-learn matplotlib seaborn pillow tqdm


# %% CELL 2 — imports + config ------------------------------------------------
import os, json, gc, shutil, subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from PIL import Image
from tqdm.auto import tqdm
from scipy.stats import spearmanr, rankdata
import matplotlib.pyplot as plt
import seaborn as sns

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", DEVICE)
assert DEVICE == "cuda", "Runtime -> Change runtime type -> T4 GPU"

ROOT        = Path("/content/memcat_proj"); ROOT.mkdir(exist_ok=True)
ACT_DIR     = ROOT / "activations"; ACT_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR     = ROOT / "figures";     FIG_DIR.mkdir(parents=True, exist_ok=True)
BATCH       = 64
NUM_WORKERS = 4        # NOTE: if extraction is slow, drop to 2 OR copy images
                       # from Drive to /content/images first — Drive I/O is the
                       # bottleneck and >2 workers can thrash it.
USE_ALL     = True
N_PER_CLASS = 100

# CLIP feature head: 'cls' (default, what CLIP was trained on)
# or 'patch_mean' (matches ResNet's avg-pool symmetry).
# We will run BOTH and compare to make sure conclusions don't flip.
CLIP_HEADS = ["cls", "patch_mean"]


# %% CELL 3 — mount Drive, set paths, wipe stale state ------------------------
from google.colab import drive
drive.mount('/content/drive')

IMG_DIR  = Path("/content/drive/MyDrive/MemCat_data/MemCat")
META_CSV = ROOT / "memcat_meta.csv"

subprocess.run("rm -rf /content/memcat_proj/images", shell=True)
META_CSV.unlink(missing_ok=True)
subprocess.run(f"rm -f {ACT_DIR}/*.npz", shell=True)

shutil.copy("/content/drive/MyDrive/MemCat_data/memcat_image_data.csv", META_CSV)
assert IMG_DIR.exists() and META_CSV.exists()
print("IMG_DIR :", IMG_DIR)
print("META_CSV:", META_CSV)


# %% CELL 4 — load + harmonize metadata ---------------------------------------
meta_raw = pd.read_csv(META_CSV)
rename_map = {}
for c in meta_raw.columns:
    lc = c.lower().strip()
    if lc == "image_file":                   rename_map[c] = "filename"
    if lc == "category":                     rename_map[c] = "category"
    if lc == "subcategory":                  rename_map[c] = "subcategory"
    if lc == "memorability_w_fa_correction": rename_map[c] = "memorability"
meta = meta_raw.rename(columns=rename_map)
if "Unnamed: 0" in meta.columns:
    meta = meta.drop(columns=["Unnamed: 0"])

need = {"filename", "category", "subcategory", "memorability"}
assert need <= set(meta.columns), f"missing {need - set(meta.columns)}"
print("columns ok. memorability range:",
      f"{meta['memorability'].min():.3f} .. {meta['memorability'].max():.3f}")


# %% CELL 5 — resolve image paths (~2-4 min over Drive) -----------------------
print("indexing Drive...")
by_cat_sub_base, by_cat_base, by_basename = {}, {}, {}
for p in tqdm(IMG_DIR.rglob("*.jpg"), desc="indexing"):
    rel   = p.relative_to(IMG_DIR); parts = rel.parts; base = parts[-1]
    by_basename.setdefault(base, []).append(p)
    if len(parts) >= 2: by_cat_base[(parts[0], base)] = p
    if len(parts) >= 3: by_cat_sub_base[(parts[0], parts[1], base)] = p

def resolve_path(row):
    fn  = str(row["filename"])
    cat = str(row.get("category", "")).lower().strip()
    sub = str(row.get("subcategory", "")).lower().strip()
    if (cat, sub, fn) in by_cat_sub_base: return by_cat_sub_base[(cat, sub, fn)]
    if (cat, fn) in by_cat_base:          return by_cat_base[(cat, fn)]
    cands = by_basename.get(fn, [])
    if len(cands) == 1:                    return cands[0]
    return None

meta["path"] = meta.apply(resolve_path, axis=1)
dropped = meta["path"].isna().sum()
meta = meta.dropna(subset=["path"]).reset_index(drop=True)
print(f"rows after path resolution: {len(meta)} (dropped {dropped})")


# %% CELL 6 — animacy mapping (FIX E) -----------------------------------------
# 'sports' is a context category (people in stadiums, equipment, crowds, ...)
# and conflates animate subjects with inanimate context. We DROP it from the
# main analysis. The clean comparison is:
#     animate   = {animal}
#     inanimate = {food, landscape, vehicle}
ANIMATE_SUPER   = {"animal"}
INANIMATE_SUPER = {"food", "landscape", "vehicle"}

def animacy(cat):
    cat = str(cat).lower().strip()
    if cat in ANIMATE_SUPER:   return "animate"
    if cat in INANIMATE_SUPER: return "inanimate"
    return "unknown"      # sports + anything else -> excluded

meta["animacy"] = meta["category"].map(animacy)
n_dropped_sports = int((meta["category"].str.lower().str.strip() == "sports").sum())
meta = meta[meta["animacy"] != "unknown"].reset_index(drop=True)
print(f"dropped {n_dropped_sports} 'sports' images (excluded from animacy comparison)")
print("after animacy filter:", meta["animacy"].value_counts().to_dict())

if not USE_ALL:
    meta = (meta.groupby("animacy", group_keys=False)
                 .apply(lambda g: g.sample(n=N_PER_CLASS, random_state=0))
                 .reset_index(drop=True))
    print("post-subsample:", meta["animacy"].value_counts().to_dict())

print("total images:", len(meta))


# %% CELL 7 — model builders (ResNet50 + CLIP heads) --------------------------
import timm, open_clip

def build_resnet50():
    m = timm.create_model("resnet50", pretrained=True, num_classes=0, global_pool="avg")
    m.eval().to(DEVICE)
    cfg  = timm.data.resolve_data_config({}, model=m)
    prep = timm.data.create_transform(**cfg)
    feats = {}
    def hook(_, __, out): feats["s"] = out.detach()
    m.layer4.register_forward_hook(hook)
    def feat(x):
        with torch.no_grad(): return m(x)
    def spatial(x):
        with torch.no_grad(): m(x); return feats["s"]
    return feat, prep, spatial

def build_clip_vitb16(head="cls"):
    """
    CLIP ViT-B/16 with selectable feature head.
      head='cls'        -> CLS token (what CLIP was trained on; the canonical choice)
      head='patch_mean' -> mean over patch tokens (matches ResNet avg-pool symmetry)
    """
    assert head in ("cls", "patch_mean")
    model, _, prep = open_clip.create_model_and_transforms(
        "ViT-B-16-quickgelu", pretrained="openai"
    )
    visual = model.visual.eval().to(DEVICE)

    hooked = {}
    def hook(_, __, o):
        hooked["tok"] = o.detach()
    visual.transformer.resblocks[-1].register_forward_hook(hook)

    def _to_NLD(tok, B):
        if tok.shape[0] == B: return tok
        if tok.shape[1] == B: return tok.transpose(0, 1)
        raise RuntimeError(f"unexpected CLIP hook shape {tok.shape} for B={B}")

    def feat(x):
        B = x.shape[0]
        with torch.no_grad():
            _ = visual(x)
            tok = _to_NLD(hooked["tok"], B).contiguous()
            if head == "cls":
                return tok[:, 0, :]              # CLS
            else:
                return tok[:, 1:, :].mean(dim=1) # patch mean

    def spatial(x):
        B = x.shape[0]
        with torch.no_grad():
            _ = visual(x)
            tok = _to_NLD(hooked["tok"], B).contiguous()
            patches = tok[:, 1:, :]
            H = W = int(patches.shape[1] ** 0.5)
            return patches.transpose(1, 2).reshape(B, -1, H, W)

    return feat, prep, spatial

MODEL_BUILDERS = {
    "ResNet50":          build_resnet50,
    "CLIP_cls":          lambda: build_clip_vitb16(head="cls"),
    "CLIP_patch_mean":   lambda: build_clip_vitb16(head="patch_mean"),
}


# %% CELL 8 — FAST batched extraction (parallel loaders + fp16) --------------
# FIX C: keep prep + spatial_fn in a registry so Cell 12 can reuse them.
class PreppedDS(Dataset):
    def __init__(self, paths, prep):
        self.paths, self.prep = paths, prep
    def __len__(self): return len(self.paths)
    def __getitem__(self, i):
        return self.prep(Image.open(self.paths[i]).convert("RGB"))

MODEL_REGISTRY = {}     # name -> {'feat': fn, 'prep': transform, 'spatial': fn}

def extract_activations_fast(name, builder, batch_size=BATCH, num_workers=NUM_WORKERS):
    cache = ACT_DIR / f"{name.replace('/','_')}.npz"
    if cache.exists():
        arr = np.load(cache, allow_pickle=False)["acts"]
        if arr.shape[0] == len(meta):
            print(f"[{name}] cached {arr.shape}")
            # still need prep/spatial for later cells
            feat_fn, prep, spatial_fn = builder()
            MODEL_REGISTRY[name] = dict(feat=feat_fn, prep=prep, spatial=spatial_fn)
            return arr
        print(f"[{name}] stale cache {arr.shape}; re-extracting")
        cache.unlink()

    feat_fn, prep, spatial_fn = builder()
    MODEL_REGISTRY[name] = dict(feat=feat_fn, prep=prep, spatial=spatial_fn)

    ds = PreppedDS(meta["path"].tolist(), prep)
    loader = DataLoader(ds, batch_size=batch_size, num_workers=num_workers,
                        shuffle=False, pin_memory=True)

    all_acts = []
    for x in tqdm(loader, desc=f"extract {name}"):
        x = x.to(DEVICE, non_blocking=True)
        with torch.no_grad(), torch.cuda.amp.autocast():
            a = feat_fn(x).float().cpu().numpy()
        all_acts.append(a)
    acts = np.concatenate(all_acts, axis=0)
    np.savez_compressed(cache, acts=acts)
    print(f"[{name}] saved {acts.shape}")
    torch.cuda.empty_cache(); gc.collect()
    return acts

activations = {}
for name, b in MODEL_BUILDERS.items():
    activations[name] = extract_activations_fast(name, b)

for m, a in activations.items():
    assert a.shape[0] == len(meta), f"{m} shape {a.shape} != meta {len(meta)}"
print("all shapes match meta")


# %% CELL 9 — selectivity index (FIX A) ---------------------------------------
# Standard Cohen's-d / d-prime: difference of group means divided by pooled
# WITHIN-group SD on the RAW activations. The earlier version z-scored across
# all images first, which absorbs the between-group difference into the scale
# and biases d' toward zero.
def selectivity(acts, labels):
    a = acts[labels == "animate"]
    i = acts[labels == "inanimate"]
    pooled_sd = np.sqrt(0.5 * (a.var(0) + i.var(0)) + 1e-8)
    return (a.mean(0) - i.mean(0)) / pooled_sd

labels = meta["animacy"].values
sel = {m: selectivity(a, labels) for m, a in activations.items()}
print("selectivity computed:", list(sel.keys()))


# %% CELL 10 — FIGURE 1: selectivity distributions ---------------------------
sns.set_style("whitegrid")
fig, ax = plt.subplots(figsize=(8.5, 5))
palette = {"ResNet50": "#1f77b4", "CLIP_cls": "#2ca02c", "CLIP_patch_mean": "#d62728"}
for m, s in sel.items():
    sns.kdeplot(s, label=m, ax=ax, lw=2, color=palette.get(m, None))
ax.axvline(0, color="k", lw=0.6, ls="--")
ax.set_xlabel("Animate – inanimate selectivity (d′ on raw activations, pooled within-group SD)")
ax.set_ylabel("Density (units)")
ax.set_title(f"Unit-level animacy selectivity: ResNet50 vs CLIP heads (n={len(meta)} MemCat images)")
ax.legend(frameon=False)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig1_selectivity_dist.png", dpi=160)
plt.show()

print("\nSelectivity summary (raw d', pooled within-group SD):")
for m, s in sel.items():
    print(f"  {m:18s}  |d'|>0.5: {(np.abs(s)>0.5).mean():.3f}   "
          f"|d'|>1.0: {(np.abs(s)>1.0).mean():.3f}   "
          f"animate-skewed: {(s>0).mean():.3f}   mean d': {s.mean():+.3f}")


# %% CELL 11 — FIGURE 2: top-activating images -------------------------------
def topk_images_for_unit(acts, unit_idx, k=9):
    return np.argsort(acts[:, unit_idx])[::-1][:k]

def plot_grid(ax_list, img_paths, title):
    for ax, p in zip(ax_list, img_paths):
        ax.imshow(Image.open(p).convert("RGB"))
        ax.axis("off")
    ax_list[0].set_ylabel(title, fontsize=10, rotation=0, labelpad=60, ha="right")

n_models = len(activations)
fig, axes = plt.subplots(n_models * 2, 9, figsize=(18, 3.6 * n_models))
for mi, (m, a) in enumerate(activations.items()):
    s = sel[m]
    u_a = int(np.argmax(s))
    u_i = int(np.argmin(s))
    for row, (uidx, tag) in enumerate([(u_a, f"{m}\nanimate\nunit {u_a}"),
                                        (u_i, f"{m}\ninanimate\nunit {u_i}")]):
        rr    = mi * 2 + row
        topk  = topk_images_for_unit(a, uidx, k=9)
        paths = [meta.iloc[i]["path"] for i in topk]
        plot_grid(axes[rr], paths, tag)

plt.suptitle("Top-9 activating images — most animate- and inanimate-selective unit",
             y=1.002, fontsize=12)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig2_top_images.png", dpi=140, bbox_inches="tight")
plt.show()


# %% CELL 12 — FIGURE 3: spatial activation overlay (FIX C: reuse models) ----
animate_df = meta[meta["animacy"] == "animate"].sort_values("memorability", ascending=False)
test_path = animate_df.iloc[0]["path"]
print("test image:", test_path)
test_pil = Image.open(test_path).convert("RGB")

def overlay(ax, base_pil, heat, title):
    base = np.asarray(base_pil.resize((224, 224))).astype(float) / 255.0
    heat = (heat - heat.min()) / (heat.max() - heat.min() + 1e-8)
    heat_rgb = plt.cm.jet(heat)[..., :3]
    blend = 0.55 * base + 0.45 * heat_rgb
    ax.imshow(np.clip(blend, 0, 1)); ax.axis("off"); ax.set_title(title, fontsize=10)

model_names = list(activations.keys())
fig, axes = plt.subplots(1, len(model_names) + 1,
                         figsize=(3.4 * (len(model_names) + 1), 3.6))
axes[0].imshow(test_pil.resize((224, 224))); axes[0].axis("off"); axes[0].set_title("input")

for ax, m in zip(axes[1:], model_names):
    reg = MODEL_REGISTRY[m]                       # FIX C: no rebuild
    prep, spatial_fn = reg["prep"], reg["spatial"]
    x = prep(test_pil).unsqueeze(0).to(DEVICE)
    smap = spatial_fn(x)[0].cpu().float().numpy()
    top_unit = int(np.argmax(sel[m]))
    heat = smap[top_unit]
    heat_t  = torch.tensor(heat)[None, None]
    heat_up = F.interpolate(heat_t, size=(224, 224), mode="bilinear",
                            align_corners=False)[0, 0].numpy()
    overlay(ax, test_pil, heat_up, f"{m}\nunit {top_unit}")
    torch.cuda.empty_cache()

plt.suptitle("Spatial activation of the most animate-selective unit\n"
             "(ResNet: layer4 channel; CLIP: patch grid of one hidden dimension — "
             "note this is unit activity, not saliency)", y=1.06, fontsize=10)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig3_cam_overlay.png", dpi=160, bbox_inches="tight")
plt.show()


# %% CELL 13 — FIGURE 4: memorability modulation (FIX D: vectorised CIs) -----
def _spearman_boot_vec(x, y, n_boot=1000, seed=0):
    """
    Bootstrap CI for Spearman ρ — vectorised.
    Trick: rank the original arrays once, then Pearson-correlate bootstrapped
    rank pairs (Pearson on ranks == Spearman). All bootstrap samples are
    computed in NumPy without a per-iteration scipy call.
    """
    rng = np.random.default_rng(seed)
    rx = rankdata(x); ry = rankdata(y)
    N = len(rx)
    idx = rng.integers(0, N, size=(n_boot, N))
    Rx = rx[idx]; Ry = ry[idx]
    Rxc = Rx - Rx.mean(axis=1, keepdims=True)
    Ryc = Ry - Ry.mean(axis=1, keepdims=True)
    num = (Rxc * Ryc).sum(axis=1)
    den = np.sqrt((Rxc ** 2).sum(axis=1) * (Ryc ** 2).sum(axis=1)) + 1e-12
    rhos = num / den
    return np.percentile(rhos, 2.5), np.percentile(rhos, 97.5)

def within_memorability_corr(acts, sel_vec, mem, mask, K_list=(1, 5, 20), n_boot=1000):
    top_order = np.argsort(sel_vec)[::-1]
    A = acts[mask]; M = mem[mask]
    out = {}
    for K in K_list:
        units = top_order[:K]
        score = A[:, units].mean(axis=1)
        r_point, _ = spearmanr(score, M)
        lo, hi = _spearman_boot_vec(score, M, n_boot=n_boot)
        out[K] = (r_point, lo, hi)
    return out

mem    = meta["memorability"].values
a_mask = (meta["animacy"] == "animate").values
i_mask = (meta["animacy"] == "inanimate").values

records = []
for m, a in activations.items():
    s = sel[m]
    res_a = within_memorability_corr(a,  s, mem, a_mask)
    res_i = within_memorability_corr(a, -s, mem, i_mask)
    for K, (r, lo, hi) in res_a.items():
        records.append(dict(model=m, subset="animate-within",   K=K, rho=r, lo=lo, hi=hi))
    for K, (r, lo, hi) in res_i.items():
        records.append(dict(model=m, subset="inanimate-within", K=K, rho=r, lo=lo, hi=hi))

res_df = pd.DataFrame(records)
print(res_df.to_string())

fig, axes = plt.subplots(1, 2, figsize=(11, 4.8), sharey=True)
model_order = list(activations.keys())
for ax, subset in zip(axes, ["animate-within", "inanimate-within"]):
    sub = res_df[res_df.subset == subset]
    for K, grp in sub.groupby("K"):
        grp = grp.set_index("model").loc[model_order].reset_index()
        xs = np.arange(len(grp))
        off = {1: -0.22, 5: 0, 20: 0.22}[K]
        ax.errorbar(xs + off, grp["rho"],
                    yerr=[grp["rho"] - grp["lo"], grp["hi"] - grp["rho"]],
                    fmt="o", label=f"K={K}", capsize=3)
    ax.set_xticks(np.arange(len(model_order)))
    ax.set_xticklabels(model_order, rotation=15)
    ax.axhline(0, color="k", lw=0.5, ls="--")
    ax.set_title(subset)
    ax.set_ylabel("Spearman ρ (unit activation vs. memorability)")
    ax.legend(frameon=False, fontsize=8)
plt.tight_layout()
plt.savefig(FIG_DIR / "fig4_memorability_modulation.png", dpi=160)
plt.show()


# %% CELL 14 — head-to-head check: do CLIP-cls and CLIP-patch agree? ---------
# A quick robustness check so you can defend any CLIP claim.
print("\nCLIP head agreement (do the two heads tell the same story?):")
if "CLIP_cls" in sel and "CLIP_patch_mean" in sel:
    # rank-correlate the per-unit selectivity vectors of the two heads
    rho_heads, _ = spearmanr(sel["CLIP_cls"], sel["CLIP_patch_mean"])
    print(f"  Spearman ρ between CLIP_cls and CLIP_patch_mean unit selectivities: {rho_heads:+.3f}")
    print(f"    (high = same units selective regardless of head choice)")


# %% CELL 15 — save summary --------------------------------------------------
summary = {
    "models": list(activations.keys()),
    "selectivity_stats": {m: {"mean":            float(s.mean()),
                               "frac_abs_gt_0.5": float((np.abs(s) > 0.5).mean()),
                               "frac_abs_gt_1.0": float((np.abs(s) > 1.0).mean()),
                               "animate_skew":    float((s > 0).mean())}
                          for m, s in sel.items()},
    "animacy_mapping": {"animate":   sorted(ANIMATE_SUPER),
                        "inanimate": sorted(INANIMATE_SUPER),
                        "excluded":  ["sports (context category, not animacy)"]},
    "n_images":    int(len(meta)),
    "n_animate":   int(a_mask.sum()),
    "n_inanimate": int(i_mask.sum()),
    "method_notes": {
        "selectivity":   "Cohen's d on raw activations with pooled within-group SD",
        "clip_heads":    "CLS token (canonical) AND patch-mean (ResNet-symmetric)",
        "bootstrap":     "1000 resamples, vectorised rank-Pearson",
        "correlations":  "Spearman throughout (rank-based)",
    },
}
with open(ROOT / "summary.json", "w") as f:
    json.dump(summary, f, indent=2)
print(json.dumps(summary, indent=2))
print("figures ->", FIG_DIR)